GET http://localhost:3001/users

###
POST http://localhost:3001/users/register
Content-Type: application/json

{
    "nombre": "Raul",
    "apellido": "Webito",
    "dni": "12345628B",
    "correo": "raulito@example.com",
    "contrasena": "123",
    "telefono": "123451789",
    "ruta_img_dni": "/path/to/dni.jpg",
    "ruta_img_carnet": "/path/to/carnet.jpg"
}